// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYBSXwOCaHCvQsB62xIHVUuEaQ5n0WSEQ',
    appId: '1:32500537433:web:f5a4209951d345feb23948',
    messagingSenderId: '32500537433',
    projectId: 'cuevents-1a00b',
    authDomain: 'cuevents-1a00b.firebaseapp.com',
    storageBucket: 'cuevents-1a00b.appspot.com',
    measurementId: 'G-WLW9N996YP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASSdD7OcjNqhxn6UMzvIHX8pzS8Xy186o',
    appId: '1:32500537433:android:038ae2d4039f3f24b23948',
    messagingSenderId: '32500537433',
    projectId: 'cuevents-1a00b',
    storageBucket: 'cuevents-1a00b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPBO5xxNmxV9FmcNvY9nbfsib1OyDNqNY',
    appId: '1:32500537433:ios:2e9a53d36b1f3c6cb23948',
    messagingSenderId: '32500537433',
    projectId: 'cuevents-1a00b',
    storageBucket: 'cuevents-1a00b.appspot.com',
    iosBundleId: 'com.example.cuEvents',
  );
}
